var lang = {
    error:{
        communication: 'Problème de communication',
        getFileFromBoiler: 'Impossible de récupérer les fichiers présents sur la chaudière',
        maj: 'Echec de la mise à jour',
        csvImport: "Echec de l'importation",
        summary: 'Synthèse non traitée',
        ipNotPing: "L'adresse Ip ne repond pas",
        configNotSave: 'Configuration non sauvegardée',
        csvNotFound: "Le fichier CSV de référence n'a pas été trouvé",
        getSeasons: 'Problème lors de la récupération des saisons',
        saveSeason: "Problème lors de l'enregistrement de la saison",
        seasonAlreadyExist: 'Attention, cette saison existe déjà !',
        deleteSeason: 'Problème lors de la suppresion de la saison',
        date: 'Format de la date incorrect',
        dateInvert: 'La date de début doit etre inferieur à la date de fin',
        save: 'Problème lors de la sauvegarde',
        position: 'Impossible de récupérer la derniere position',
        grapehAlreadyExist: 'Attention, le graphe existe déjà !',
        deleteGraphe: "Problème lors de la suppresion du graphe",
        assoAlreadyExist: "Attention, le couple Graphique + Capteur existe déjà",
        coeffMustBeNumber: "Le coefficient doit etre un nombre",
        update: "Problème lors de la mise à jour",
        deleteAsso: "Problème lors de la suppresion de l'association",
        getGraphe: "Impossible de charger la liste des graphiques",
        getAsso: "Impossible de charger la liste des associations",
        getSensor: "Impossible de récupérer la liste des capteurs",
        getIndicByMonth: "Problème lors de la récupération des indicateurs du mois",
        getTotalSaison: "Problème lors de la récupération des indicateurs de la saison",
        getSyntheseSaison: "Problème lors de la récupération de la synthèse de la saison",
        bddFail: "Echec de connexion à la base de données",
        passNotChanged: "Mot de passe inchangé !",
        passNotTheSame: "Les deux champs ne sont pas identiques.",
        userPassIncorrect: "User/password incorrect",
        sessionEnded: 'Session expirée'
    },
    valid:{
        communication: 'Communication établie',
        maj: 'Mise à jour réalisée avec succès',
        csvImport: 'Importation réussie',
        summary: 'Synthèse réussie',
        configSave: 'Configuration sauvegardée',
        save: 'Enregistrement réussi',
        update: 'Mise à jour réussie',
        delete: 'Suppression réussie'
    },
    text:{
        seeFileOnboiler: 'Visualiser les fichiers sur la chaudière',
        addSeason: "Ajout d'une saison",
        updateSeason: 'Modification saison',
        deleteSeason: 'Confirmez-vous la suppression de la saison',
        addGraphe: "Création d'un nouveau graphique",
        updateGraphe: 'Modification de',
        deleteGraphe: 'Confirmez-vous la suppresion de',
        updateAsso: "Modification de l'association",
        deleteAsso: "Confirmez-vous la suppresion de l'asso",
        titreHisto: 'Synthèse mensuelle',
        updateAvailable: 'Une nouvelle version Okovision est disponible, cliquez ici'
    },
    graphic:{
        thousandsSep: ' ',
        decimalPoint: ',',
        months: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin',  'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
        shortMonths: [ "Jan" , "Fev" , "Mar" , "Avr" , "Mai" , "Juin" , "Juil" , "Aout" , "Sep" , "Oct" , "Nov" , "Dec"],
        weekdays: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
        day: 'jour',
        month: 'mois',
        hour: 'Heures',
        tc: 'T°C',
        kgAndDju: 'Kg et DJU',
        nbCycle: 'Nb Cycle',
        seasonSummary: "Synthèse Saison"
    }
};
    
